name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - shubham/initialize-Codebase
  workflow_dispatch:
env:
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v3
        timeout-minutes: 20
        with:
          name: teacherbot-data-pipeline
          runtime: python310
          entry_point: main
          region: us-east1
          source_dir: .
          memory: 8Gi
          vpc_connector: cf-vpc-connector
          vpc_connector_egress_settings: ALL_TRAFFIC
          environment_variables: |-
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
            AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}
            PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
            PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
            PINECONE_INDEX_NAME=${{ secrets.PINECONE_INDEX_NAME }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            GOOGLE_APPLICATION_CREDENTIALS_JSON="${{ secrets.GCP_CREDENTIALS_ESCAPED }}"
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            CHUNK_SIZE=${{ env.CHUNK_SIZE }}
            CHUNK_OVERLAP=${{ env.CHUNK_OVERLAP }}

      - name: Confirm Deployment
        run: echo "Cloud Function 'teacherbot-data-pipeline' deployed successfully!"
